<?xml version="1.0"?>
<robot name="mobile_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 파라미터 -->
  <xacro:property name="wheel_radius" value="0.065"/> <!-- Ø130mm/2 -->
  <xacro:property name="wheel_length" value="0.4465"/> <!-- 바퀴 중심 간 거리 -->
  <xacro:property name="base_size_x"  value="0.30"/>
  <xacro:property name="base_size_y"  value="0.40"/>
  <xacro:property name="base_size_z"  value="0.10"/>

  <!-- 관성 없는 루트(표준) -->
  <link name="base_footprint"/>
  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child  link="base_link"/>
    <!-- 바닥 접점 기준으로 베이스가 바퀴 중심 높이에 오도록 -->
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- 베이스 -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${base_size_x} ${base_size_y} ${base_size_z}"/></geometry>
      <material name="chassis"><color rgba="0.2 0.2 0.25 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${base_size_x} ${base_size_y} ${base_size_z}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10.0"/>
      <inertia ixx="0.2" iyy="0.2" izz="0.2" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- 왼쪽 바퀴 -->
  <link name="wheel_left_link">
    <visual>
      <!-- 실린더 축(z)을 y축으로 회전 -->
      <origin xyz="0 0 0" rpy="1.57079632679 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="0.04"/></geometry>
      <material name="wheel"><color rgba="0.1 0.1 0.1 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.57079632679 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="0.04"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- 오른쪽 바퀴 -->
  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57079632679 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="0.04"/></geometry>
      <material name="wheel"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.57079632679 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="0.04"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- 힌지(y축 회전) : 바퀴 위치는 joint에서만 지정 -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_left_link"/>
    <origin xyz="0 ${wheel_length/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_right_link"/>
    <origin xyz="0 ${-wheel_length/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>
